/**
 * Government Schemes Module — FROZEN
 * No further feature development. Bug fixes only.
 */

import type { Scheme } from '@/lib/services/schemeService';

interface PdfScheme {
  title: string;
  titleHindi?: string;
  icon?: string;
  benefits?: string[];
  eligibility?: string[];
  documents?: string[];
  apply_process?: string[];
  official_website_url?: string;
  helpline?: string;
  last_date?: string;
  updated_at?: string;
}

function getField(s: Scheme): PdfScheme {
  const meta =
    s.id === 'pm_kisan' ? { title: 'PM Kisan Samman Nidhi', titleHindi: 'पीएम किसान सम्मान निधि', icon: '🌾' }
    : s.id === 'pm_fasal_bima' ? { title: 'PM Fasal Bima Yojana', titleHindi: 'फसल बीमा योजना', icon: '🌱' }
    : s.id === 'ayushman_bharat' ? { title: 'Ayushman Bharat PMJAY', titleHindi: 'आयुष्मान भारत', icon: '🏥' }
    : { title: s.id.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()) };
  return {
    ...meta,
    ...s,
    benefits: s.benefits as string[] | undefined,
    eligibility: s.eligibility as string[] | undefined,
    documents: s.documents as string[] | undefined,
    apply_process: s.apply_process as string[] | undefined,
  };
}

function escapeXml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function listItems(items: string[]): string {
  return items.map((item) => `<li>${escapeXml(item)}</li>`).join('');
}

function buildHtml(s: Scheme): string {
  const d = getField(s);
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${escapeXml(d.title)}</title>
<style>
  @page { margin: 20mm; }
  body { font-family: 'Noto Sans', Arial, sans-serif; color: #333; line-height: 1.6; font-size: 12px; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  .subtitle { color: #666; font-size: 13px; margin-bottom: 16px; }
  .section { margin-bottom: 20px; }
  .section h2 { font-size: 16px; border-bottom: 2px solid #1565C0; padding-bottom: 4px; margin-bottom: 8px; color: #1565C0; }
  ul { margin: 4px 0; padding-left: 20px; }
  li { margin-bottom: 3px; }
  a { color: #1565C0; }
  .meta { font-size: 11px; color: #888; margin-top: 24px; border-top: 1px solid #ddd; padding-top: 8px; }
</style>
</head>
<body>
<h1>${escapeXml(d.title)}</h1>
${d.titleHindi ? `<p class="subtitle">${escapeXml(d.titleHindi)}</p>` : ''}

${d.benefits?.length ? `<div class="section"><h2>Benefits</h2><ul>${listItems(d.benefits)}</ul></div>` : ''}
${d.eligibility?.length ? `<div class="section"><h2>Eligibility</h2><ul>${listItems(d.eligibility)}</ul></div>` : ''}
${d.documents?.length ? `<div class="section"><h2>Required Documents</h2><ul>${listItems(d.documents)}</ul></div>` : ''}
${d.apply_process?.length ? `<div class="section"><h2>Application Process</h2><ol>${listItems(d.apply_process)}</ol></div>` : ''}
${d.official_website_url ? `<div class="section"><h2>Official Website</h2><p><a href="${escapeXml(d.official_website_url)}">${escapeXml(d.official_website_url)}</a></p></div>` : ''}
${d.helpline ? `<div class="section"><h2>Helpline</h2><p>${escapeXml(d.helpline)}</p></div>` : ''}
${d.last_date ? `<div class="section"><h2>Last Date</h2><p>${escapeXml(d.last_date)}</p></div>` : ''}

<div class="meta">
  <p>Generated by GramSeva Portal</p>
  ${d.updated_at ? `<p>Last updated: ${new Date(d.updated_at).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</p>` : ''}
  <p>Source: Government of India / respective state departments</p>
</div>
</body>
</html>`;
}

export async function generatePdfBlob(scheme: Scheme): Promise<Blob> {
  const { default: jsPDF } = await import('jspdf');
  const html = buildHtml(scheme);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const iframe = document.createElement('iframe');
  iframe.style.position = 'absolute';
  iframe.style.left = '-9999px';
  iframe.style.width = '800px';
  iframe.style.height = '1200px';
  document.body.appendChild(iframe);
  iframe.src = url;
  await new Promise<void>((resolve) => {
    iframe.onload = () => {
      setTimeout(resolve, 500);
    };
  });
  try {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const docIframe = iframe.contentDocument || iframe.contentWindow!.document;
    const bodyEl = docIframe.querySelector('body')!;
    const totalHeight = bodyEl.scrollHeight;
    const pageHeight = 1120;
    const pageCount = Math.ceil(totalHeight / pageHeight);
    for (let i = 0; i < pageCount; i++) {
      if (i > 0) pdf.addPage();
      bodyEl.style.transform = `translateY(-${i * pageHeight}px)`;
      bodyEl.style.overflow = 'hidden';
      await new Promise((r) => setTimeout(r, 100));
    }
    bodyEl.style.transform = '';
    bodyEl.style.overflow = '';
    const pdfBlob = pdf.output('blob');
    return pdfBlob;
  } finally {
    document.body.removeChild(iframe);
    URL.revokeObjectURL(url);
  }
}

export async function downloadPdf(scheme: Scheme): Promise<void> {
  const blob = await generatePdfBlob(scheme);
  const d = getField(scheme);
  const filename = `${d.title.replace(/\s+/g, '_')}_GramSeva.pdf`;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
