export interface SchemeDisplay {
  title: string;
  titleHindi: string;
  description: string;
  icon: string;
  color: string;
  link: string;
  featured: boolean;
}

export const schemeDisplayMeta: Record<string, SchemeDisplay> = {
  pm_kisan: {
    title: 'PM Kisan Samman Nidhi',
    titleHindi: 'पीएम किसान सम्मान निधि',
    description: 'Small & marginal farmers get ₹6,000/year in 3 equal installments directly to their bank account.',
    icon: '🌾',
    color: '#2E7D32',
    link: '/agriculture',
    featured: true,
  },
  ayushman_bharat: {
    title: 'Ayushman Bharat PMJAY',
    titleHindi: 'आयुष्मान भारत',
    description: 'Health coverage up to ₹5 lakh per year for secondary & tertiary hospitalization for eligible families.',
    icon: '🏥',
    color: '#C62828',
    link: '/health',
    featured: true,
  },
  pm_awas_rural: {
    title: 'PM Awas Yojana',
    titleHindi: 'प्रधानमंत्री आवास योजना',
    description: 'Housing assistance for rural & urban poor. Subsidized housing for eligible BPL families.',
    icon: '🏘️',
    color: '#1565C0',
    link: '/housing',
    featured: true,
  },
  pm_fasal_bima: {
    title: 'PM Fasal Bima Yojana',
    titleHindi: 'फसल बीमा योजना',
    description: 'Crop insurance scheme providing financial support to farmers suffering crop loss due to natural calamities.',
    icon: '🌱',
    color: '#6A1B9A',
    link: '/agriculture',
    featured: true,
  },
  nsp: {
    title: 'National Scholarship Portal',
    titleHindi: 'राष्ट्रीय छात्रवृत्ति पोर्टल',
    description: 'Government scholarships for SC/ST/OBC & minority students for higher education.',
    icon: '🎓',
    color: '#E65100',
    link: '/education',
    featured: true,
  },
  pm_mudra: {
    title: 'PM Mudra Yojana',
    titleHindi: 'पीएम मुद्रा योजना',
    description: 'Collateral-free loans up to ₹10 lakh for non-farm small/micro enterprises.',
    icon: '💼',
    color: '#00695C',
    link: '/jobs',
    featured: true,
  },
  kcc: {
    title: 'Kisan Credit Card',
    titleHindi: 'किसान क्रेडिट कार्ड',
    description: 'Easy credit facility for farming needs with low interest rates.',
    icon: '💳',
    color: '#2E7D32',
    link: '/agriculture',
    featured: false,
  },
  soil_health_card: {
    title: 'Soil Health Card',
    titleHindi: 'मृदा स्वास्थ्य कार्ड',
    description: 'Free soil testing & crop-wise fertilizer recommendations.',
    icon: '🌱',
    color: '#F57F17',
    link: '/agriculture',
    featured: false,
  },
  pm_krishi_sinchai: {
    title: 'PM Krishi Sinchai Yojana',
    titleHindi: 'कृषि सिंचाई योजना',
    description: 'Irrigation infrastructure & water efficiency for every field.',
    icon: '💧',
    color: '#00695C',
    link: '/agriculture',
    featured: false,
  },
  enam: {
    title: 'e-NAM Portal',
    titleHindi: 'ई-नाम पोर्टल',
    description: 'Online trading platform for agricultural commodities.',
    icon: '📊',
    color: '#BF360C',
    link: '/agriculture',
    featured: false,
  },
  pm_awas_urban: {
    title: 'PM Awas Yojana (Urban)',
    titleHindi: 'पीएम आवास योजना (शहरी)',
    description: 'Housing for urban poor with credit linked subsidy.',
    icon: '🏘️',
    color: '#1565C0',
    link: '/housing',
    featured: false,
  },
  housing_subsidy: {
    title: 'Housing Subsidy Scheme',
    titleHindi: 'आवास सब्सिडी',
    description: 'Interest subsidy on home loans for EWS/LIG/MIG categories.',
    icon: '🏠',
    color: '#1565C0',
    link: '/housing',
    featured: false,
  },
  abha_health_id: {
    title: 'ABHA Health ID',
    titleHindi: 'आभा स्वास्थ्य आईडी',
    description: 'Digital health ID for seamless access to health records.',
    icon: '🩺',
    color: '#C62828',
    link: '/health',
    featured: false,
  },
  jan_aushadhi: {
    title: 'Jan Aushadhi Scheme',
    titleHindi: 'जन औषधि योजना',
    description: 'Quality generic medicines at affordable prices.',
    icon: '💊',
    color: '#C62828',
    link: '/health',
    featured: false,
  },
  pre_matric: {
    title: 'Pre-Matric Scholarship',
    titleHindi: 'प्री-मैट्रिक छात्रवृत्ति',
    description: 'Scholarship for SC/ST/OBC students in classes 9th & 10th.',
    icon: '📚',
    color: '#E65100',
    link: '/education',
    featured: false,
  },
  scholarship_post_matric: {
    title: 'Post-Matric Scholarship',
    titleHindi: 'पोस्ट-मैट्रिक छात्रवृत्ति',
    description: 'Scholarship for SC/ST/OBC students in classes 11th and above.',
    icon: '🎓',
    color: '#E65100',
    link: '/education',
    featured: false,
  },
  ews_scholarship: {
    title: 'EWS Scholarship',
    titleHindi: 'ईडब्ल्यूएस छात्रवृत्ति',
    description: 'Scholarship for Economically Weaker Section students.',
    icon: '🏅',
    color: '#E65100',
    link: '/education',
    featured: false,
  },
  minority_scholarship: {
    title: 'Minority Scholarship',
    titleHindi: 'अल्पसंख्यक छात्रवृत्ति',
    description: 'Scholarship for minority community students.',
    icon: '🏅',
    color: '#E65100',
    link: '/education',
    featured: false,
  },
  sukanya_samriddhi: {
    title: 'Sukanya Samriddhi Yojana',
    titleHindi: 'सुकन्या समृद्धि योजना',
    description: 'Savings scheme for girl child with high interest rate.',
    icon: '👧',
    color: '#6A1B9A',
    link: '/education',
    featured: false,
  },
  beti_bachao: {
    title: 'Beti Bachao Beti Padhao',
    titleHindi: 'बेटी बचाओ बेटी पढ़ाओ',
    description: 'Initiative to save and educate the girl child.',
    icon: '👶',
    color: '#C62828',
    link: '/education',
    featured: false,
  },
  pm_matru_vandana: {
    title: 'PM Matru Vandana Yojana',
    titleHindi: 'पीएम मातृ वंदना योजना',
    description: 'Cash incentive for pregnant & lactating mothers.',
    icon: '🤰',
    color: '#C62828',
    link: '/health',
    featured: false,
  },
  old_age_pension: {
    title: 'Old Age Pension',
    titleHindi: 'वृद्धावस्था पेंशन',
    description: 'Monthly pension for senior citizens below poverty line.',
    icon: '👴',
    color: '#4E342E',
    link: '/profile',
    featured: false,
  },
  widow_pension: {
    title: 'Widow Pension',
    titleHindi: 'विधवा पेंशन',
    description: 'Monthly pension support for widows in need.',
    icon: '👩',
    color: '#4E342E',
    link: '/profile',
    featured: false,
  },
  disability_pension: {
    title: 'Disability Pension',
    titleHindi: 'विकलांग पेंशन',
    description: 'Monthly pension for persons with disabilities.',
    icon: '♿',
    color: '#4E342E',
    link: '/profile',
    featured: false,
  },
  atal_pension: {
    title: 'Atal Pension Yojana',
    titleHindi: 'अटल पेंशन योजना',
    description: 'Guaranteed pension for unorganized sector workers.',
    icon: '🏦',
    color: '#1565C0',
    link: '/profile',
    featured: false,
  },
  pm_jan_dhan: {
    title: 'PM Jan Dhan Yojana',
    titleHindi: 'पीएम जन धन योजनa',
    description: 'Zero balance bank accounts with RuPay card & insurance.',
    icon: '🏦',
    color: '#1565C0',
    link: '/profile',
    featured: false,
  },
  stand_up_india: {
    title: 'Stand Up India',
    titleHindi: 'स्टैंड अप इंडिया',
    description: 'Bank loans for SC/ST and women entrepreneurs.',
    icon: '🚀',
    color: '#00695C',
    link: '/jobs',
    featured: false,
  },
  startup_india: {
    title: 'Startup India',
    titleHindi: 'स्टार्टअप इंडिया',
    description: 'Tax benefits & funding support for startups.',
    icon: '🚀',
    color: '#00695C',
    link: '/jobs',
    featured: false,
  },
  ration_card: {
    title: 'Ration Card',
    titleHindi: 'राशन कार्ड',
    description: 'Subsidized food grains for eligible families under PDS.',
    icon: '🛒',
    color: '#4E342E',
    link: '/profile',
    featured: false,
  },
  ujjwala: {
    title: 'Ujjwala Yojana',
    titleHindi: 'उज्ज्वला योजना',
    description: 'Free LPG connection for BPL households.',
    icon: '🔥',
    color: '#BF360C',
    link: '/profile',
    featured: false,
  },
  jal_jeevan: {
    title: 'Jal Jeevan Mission',
    titleHindi: 'जल जीवन मिशन',
    description: 'Piped water supply to every rural household.',
    icon: '💧',
    color: '#1565C0',
    link: '/profile',
    featured: false,
  },
  swachh_bharat: {
    title: 'Swachh Bharat Mission',
    titleHindi: 'स्वच्छ भारत मिशन',
    description: 'Toilet construction & solid waste management.',
    icon: '🧹',
    color: '#F57F17',
    link: '/profile',
    featured: false,
  },
};
