/**
 * ==========================================================
 * AI MODULE — FROZEN
 * ----------------------------------------------------------
 * Production Complete.
 * No further feature development.
 * Bug fixes only.
 * ==========================================================
 */

import type { Conversation, ExportFormat } from './types';
import { getModuleTitle } from './prompts';

function generateMarkdown(conv: Conversation): string {
  const lines: string[] = [];
  lines.push(`# ${conv.title}`);
  lines.push(`**Module:** ${getModuleTitle(conv.module)}`);
  lines.push(`**Date:** ${new Date(conv.createdAt).toLocaleDateString('en-IN')}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const msg of conv.messages) {
    if (msg.role === 'system') continue;
    const label = msg.role === 'user' ? '**You**' : '**AI**';
    const time = new Date(msg.timestamp).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
    lines.push(`${label} _(${time})_`);
    lines.push('');
    lines.push(msg.content);
    lines.push('');
  }

  return lines.join('\n');
}

function generatePlainText(conv: Conversation): string {
  const lines: string[] = [];
  lines.push(conv.title);
  lines.push(`Module: ${getModuleTitle(conv.module)}`);
  lines.push(`Date: ${new Date(conv.createdAt).toLocaleDateString('en-IN')}`);
  lines.push('');
  lines.push('='.repeat(40));
  lines.push('');

  for (const msg of conv.messages) {
    if (msg.role === 'system') continue;
    const label = msg.role === 'user' ? 'YOU' : 'AI';
    const time = new Date(msg.timestamp).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
    lines.push(`[${label}] (${time})`);
    lines.push(msg.content);
    lines.push('');
  }

  return lines.join('\n');
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function exportConversation(conv: Conversation, format: ExportFormat): Promise<void> {
  const safeTitle = (conv.title || 'conversation').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 50);
  const timestamp = new Date(conv.createdAt).toISOString().slice(0, 10);

  switch (format) {
    case 'markdown': {
      const md = generateMarkdown(conv);
      downloadFile(md, `${safeTitle}_${timestamp}.md`, 'text/markdown');
      break;
    }
    case 'text': {
      const txt = generatePlainText(conv);
      downloadFile(txt, `${safeTitle}_${timestamp}.txt`, 'text/plain');
      break;
    }
    case 'pdf': {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 15;
      const maxWidth = pageWidth - 2 * margin;
      let y = 20;

      doc.setFontSize(14);
      doc.text(conv.title, pageWidth / 2, y, { align: 'center' });
      y += 10;

      doc.setFontSize(9);
      doc.text(`${getModuleTitle(conv.module)} | ${new Date(conv.createdAt).toLocaleDateString('en-IN')}`, pageWidth / 2, y, { align: 'center' });
      y += 12;

      for (const msg of conv.messages) {
        if (msg.role === 'system') continue;
        if (y > 260) {
          doc.addPage();
          y = 20;
        }
        const label = msg.role === 'user' ? 'You' : 'AI';
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text(label, margin, y);
        doc.setFont('helvetica', 'normal');
        y += 5;

        const lines = doc.splitTextToSize(msg.content, maxWidth);
        doc.text(lines, margin, y);
        y += lines.length * 4.5 + 4;
      }

      doc.setFontSize(7);
      doc.text(`Generated by GramSeva AI | ${new Date().toLocaleString('en-IN')}`, margin, doc.internal.pageSize.getHeight() - 10);

      doc.save(`${safeTitle}_${timestamp}.pdf`);
      break;
    }
  }
}
